AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    dynamodb_event_reader

    Sample SAM Template for dynamodb_event_reader to interact with DynamoDB Events.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 5

Resources:

    GetSinglePostById:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: get_post/
            Handler: app.lambda_handler
            Runtime: python3.9

    CreateNewPost:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: create_new_post/
            Handler: app.lambda_handler
            Runtime: python3.9
        Description: Create a new post
        