AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    Word of Mouf

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 5

Resources:

    GetSinglePostById:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: get_post/
            Handler: app.lambda_handler
            Runtime: python3.9

    CreateNewPost:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: create_new_post/
            Handler: app.lambda_handler
            Runtime: python3.9
        Description: Create a new post
        Metadata:
            Author: Jslowik
        UpdateReplacePolicy: Delete

    GetAllPosts:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: get_all_posts/
            Handler: app.lambda_handler
            Runtime: python3.9